[package]
name = "exdb-replication"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
exdb-core = { workspace = true }
exdb-tx = { workspace = true }
exdb-storage = { workspace = true }
futures-util = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
