/**
 * @internal
 * Wire-protocol types and low-level sender abstraction.
 *
 * These types mirror the JSON message shapes the server sends and receives.
 * They are intentionally **not** re-exported from the package index — they are
 * an implementation detail of the transport layer.
 */

// ── Sender ────────────────────────────────────────────────────────────────────

/**
 * A function that serialises a payload as a JSON WebSocket message and returns
 * the server's raw response.
 *
 * Defined here so session classes can be constructed without holding a direct
 * reference to `DbClient`, which avoids circular module imports.
 */
export type Sender = (payload: Record<string, unknown>) => Promise<unknown>;

// ── Base shapes ───────────────────────────────────────────────────────────────

export interface BaseResponse {
  req_id: number;
  ok: boolean;
  error?: string;
}

interface OkResponse extends BaseResponse {
  ok: true;
}

// ── Response shapes ───────────────────────────────────────────────────────────

export interface TxResponse extends OkResponse {
  /** Opaque server-assigned transaction handle. */
  tx: string;
}

export interface DocIdResponse extends OkResponse {
  /** 32-char hex document ID generated by the server. */
  doc_id: string;
}

export interface DocResponse extends OkResponse {
  /** The document payload, or `null` when not found / deleted. */
  doc: Record<string, unknown> | null;
}

export interface DocsResponse extends OkResponse {
  /** Array of matched document payloads. */
  docs: Record<string, unknown>[];
}

export interface DocIdsResponse extends OkResponse {
  /** Array of matched document IDs. */
  doc_ids: string[];
}

export interface IndexIdResponse extends OkResponse {
  /** Server-assigned numeric index identifier. */
  index_id: number;
}

export interface IndexStateResp extends OkResponse {
  /** Human-readable index state, e.g. `"Building { … }"` or `"Ready { … }"`. */
  state: string;
}

export interface CommitMutationResponse extends OkResponse {
  result: "committed" | "conflict";
  /** Logical commit timestamp; present only when `result === "committed"`. */
  commit_ts?: number;
}

export interface CommitQueryResponse extends OkResponse {
  subscribed: boolean;
  /** Present only when `subscribed === true`. */
  sub_id?: number;
  /** True when the snapshot was invalidated before the query finished executing. */
  invalidated_during_run?: boolean;
}
