[package]
name = "exdb-cli"
version.workspace = true
edition.workspace = true

[dependencies]
exdb = { workspace = true }
exdb-storage = { workspace = true }
exdb-wire = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
